### ISSUE TITLE
Error in make_patches if patchsize in config.ini is equal to patchsize and no mask was specified.

### ISSUE THREAD

**Issue by cwlkr** [choosehappy/PatchSorter#15]
Error in make_patches if patchsize in config.ini is equal to tilesize of ROI and no mask corresponding mask is provided.
Error reproduced in PS v5.8.

Traceback from PatchSorter.

 ERROR: Traceback (most recent call last):
 File "./approaches/make_patches/make_patch_database.py", line 251, in <module>	rows, cols = np.unravel_index(idx_out, idxs.shape)
File "<\_\_array_function\_\_ internals>", line 5, in unravel_index
TypeError: only int indices permitted

Issue arises from line 245:

               idxs = np.asarray(range((imgshape_orig[0] - patchsize) * (imgshape_orig[1] - patchsize))).reshape(
                    np.asarray(imgshape_orig)[0:2] - patchsize)

Patchsize gets subtracted from imgshape_orig but idxs should be equal to the unpadded image and padding is added to idx later on. Further, if imgshape is equal to patchsize this will result in an empty array leading to a type error in np.unravel_index.

Fix replace line 245-246:
      idxs = np.asarray(range((imgshape_orig[0] ) * (imgshape_orig[1] ))).reshape(
                    np.asarray(imgshape_orig)[0:2])

**Comment by choosehappy** [comment]
yea!! good eye, thanks!
