### ISSUE TITLE
Incorrect Initialization of _pool Leading to AttributeError in Asynchronous Task Execution

### ISSUE THREAD

**Issue by jeginderof** [choosehappy/PatchSorter#20]
**Error Massage:**

  File "C:\Users\saer\PatchSorter\PS_pool.py", line 115, in add_async_job
    PS_db._pool.apply_async(what_to_run, args=arguments_and_job,
   
AttributeError: 'list' object has no attribute 'apply_async'

**Description:**
We have encountered an issue in our codebase where the _pool variable is mistakenly initialized as an empty list (_pool = [ ] ). This variable is intended to manage asynchronous tasks, but due to its incorrect initialization, calling _pool.apply_async( ) results in an AttributeError as the list object does not have the apply_async method.

This issue affects all functionalities relying on _pool for executing asynchronous operations, leading to a failure in task execution and handling.

**Comment by jacksonjacobs1** [comment]
Thanks for catching this! We'll fix the bug shortly. 

Additionally, can you provide some context about what user actions caused the error? 

After `_pool` is set to an empty list as you pointed out, it's set again here:
https://github.com/choosehappy/PatchSorter/blob/1e5f7c1911e9f6f77dfb9c05159289c9d6bbdc86/PS.py#L151

So the asyncronous job which triggered your error must have occurred before the above line was run.

**Comment by jeginderof** [comment]
After uploading an image along with a QA mask and subsequently executing make_patches, I encountered an error. Initially, this issue arose while I was using Python version 3.12. However, after setting up my environment with Python 3.8, the error no longer appears. Additionally, it seems crucial to install the exact versions of the libraries specified in the requirements.txt file; otherwise, the PatchSorter does not function correctly.

**Comment by choosehappy** [comment]
yup, all the requirements are quite precise. this is increasingly common with software packages. i would recommend taking a look at the docker containers, this basically does all of this for you without the fuss
