### ISSUE TITLE
Training DL model error

### ISSUE THREAD

**Issue by mina0107** [choosehappy/PatchSorter#22]
Hello,
Thank you for a nice tool. I have been trying to train the DL model but I am receiving "  ERROR: train_dl (job 14) failed." without more info. Could you help or advise any solution?

Thank you,
Best

**Comment by choosehappy** [comment]
Thanks for reaching out - can you describe your environment, how you set things up and what steps you've taken?

There as well are log files (ending in .log) can you send those over?
________________________________
From: mina0107 ***@***.***>
Sent: Monday, August 12, 2024 11:33 PM
To: choosehappy/PatchSorter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [choosehappy/PatchSorter] Training DL model error (Issue #22)


Hello,
Thank you for a nice tool. I have been trying to train the DL model but I am receiving " ERROR: train_dl (job 14) failed." without more info. Could you help or advise any solution?

Thank you,
Best

**Comment by mina0107** [comment]
Here is the log file of all the jobs.
[jobs.log](https://github.com/user-attachments/files/16602985/jobs.log)
I am using an EC2 with two gpus, it's an Ubuntu machine. I created an env like below:
conda create -n patchsorter python=3.8
conda activate patchsorter
pip3 -r install requirements

All the steps were successful for installation.

**Comment by mina0107** [comment]
I upgrade torch to 1.9.1 and the issue has been resolved

**Comment by choosehappy** [comment]
great news! were you using e.g., the docker container and/or the requirements file? i'm surprised it didn't work with the version pinned by us?

On 14/08/2024 19:00, mina0107 wrote:

Closed #22<https://github.com/choosehappy/PatchSorter/issues/22> as completed.

**Comment by mina0107** [comment]
I used the requirements file for installation. In addition, I had to install "sudo apt-get install libtinfo5" to run it.
